apiVersion: extensions/v1beta1
kind: Ingress
metadata:  
  name: nginx-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 3000
        path: /
      - backend:
          serviceName: app
          servicePort: 3000
        path: /items


