apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sql
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: vm
    path: /data/mysql-pv