apiVersion: apps/v1
kind: Deployment
metadata:  
  name: todo-frontend
  labels:
    app: todo-frontend
spec:
  selector:
      matchLabels:
        app: todo-frontend
  replicas: 2
  template:
    metadata:      
      labels:
        app: todo-frontend
    spec:
      containers:
      - image: ausard/todo-frontend
        name: frontend
        ports:
          - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        stdin: true
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-frontend
  name: frontend
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: todo-frontend
