apiVersion: apps/v1
kind: Deployment
metadata:  
  name: todo-frontend
  labels:
    app: todo-frontend
    tier: frontend
    track: canary
spec:
  selector:
      matchLabels:
        app: todo-frontend
  replicas: 4
  minReadySeconds: 40
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:      
      labels:
        app: todo-frontend
        tier: frontend
        track: canary
    spec:
      containers:
      - image: ausard/todo-frontend:latest
        imagePullPolicy: Always
        name: frontend
        ports:
          - containerPort: 3000
        # resources:
        #   requests:
        #     memory: "256Mi"
        #     cpu: "500m"
        #   limits:
        #     memory: "512Mi"
        #     cpu: "1000m"
        stdin: true
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-frontend
  name: frontend
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: todo-frontend
