apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_HOST: mysql
  MYSQL_DATABASE: "todo"
  MYSQL_RANDOM_ROOT_PASSWORD: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_USER: dG9kbw==
  MYSQL_PASSWORD: c2VjcmV0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
      app: mysql
spec:
  selector:
      matchLabels:
        app: mysql
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:      
      labels:
        app: mysql
    spec:    
      containers:
      - envFrom:
        - configMapRef:
            name: mysql-config
        - secretRef:              
            name: mysql-secret
        image: mysql:5.7
        name: mysql
        ports:
          - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      restartPolicy: Always
      volumes:
      - name: mysql-data
        # hostPath:
        #   path: /data/mysql-data/        
        #   type: Directory
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306      
      targetPort: 3306
  selector:
    app: mysql
